import express, { Request, Response } from "express";
import dotenv from "dotenv";
import cookieParser from "cookie-parser";
import bodyParser from "body-parser";
import "reflect-metadata";
import swaggerUi from "swagger-ui-express";
import { dataSource } from "./config/dataSource";
import swaggerDocument from "./swagger/swagger.json"; // Được tạo tự động bởi tsoa
import { RegisterRoutes } from "./routes/routes"; // Generated by tsoa
import { errorHandler } from "Middlewares/ErrorHandle";
// Tạo server Express
const app = express();
app.use(bodyParser.json());
app.use(express.json());
// set up cookies
app.use(cookieParser());
dotenv.config();
// Khởi tạo kết nối đến cơ sở dữ liệu
// Cấu hình Swagger UI
app.use("/docs", swaggerUi.serve, async (_req: Request, res: Response) => {
  res.send(swaggerUi.generateHTML(swaggerDocument));
});

RegisterRoutes(app);

app.use(errorHandler);
dataSource
  .initialize()
  .then(() => {
    console.log("Kết nối đến cơ sở dữ liệu thành công!");
  })
  .catch((error) => {
    console.error("Lỗi khi kết nối đến cơ sở dữ liệu:", error);
  });

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server đang chạy tại http://localhost:${PORT}`);
});
